export const MAX_WIDTH = 1452;

export const projects = [
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
  {
    name: "Dani Piva",
    location: "Karlovac",
    image: "/images/dani_piva.jpg",
    date: "08/21",
    category: "Događaj",
  },
];
